name: safe_bikes_map
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.9.0
  http: ^1.2.2
  google_places_flutter: ^2.0.9
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  intl_utils: ^2.8.7
  hive_generator: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
